# Generated by Django 4.2.2 on 2023-06-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
